[app]
host = "0.0.0.0"
port = 18081

[database]
host = "127.0.0.1"
name = "coin_zeus"
user = "root"
password = "Yan123456"
port = 13306

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""
